In [3]:
# Libs
import numpy as np

# NumPy Array

- How to create an empty and a full NumPy array?

In [20]:
# Empty array
empty_np_array = np.empty((2,2))
print(f'Empty Array:\n\n {empty_np_array}\n')
#Full array
full_array = np.full((2,2), 25.0)
print(f'Full Array: \n\n {full_array}')

Empty Array:

 [[1.28822975e-231 2.32036043e+077]
 [1.29074334e-231 2.82475776e-309]]

Full Array: 

 [[25. 25.]
 [25. 25.]]



- Create a Numpy array filled with all zeros

In [25]:
# Zeroes Array
zeroes_array = np.zeros((5,5))
print(f'Zeroes Array: \n\n  {zeroes_array}\n')

Zeroes Array: 

  [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]




- Create a Numpy array filled with all ones

In [27]:
# Ones Array
ones_array = np.ones((5,5))
print(f'Ones Array: \n\n  {ones_array}\n')

Ones Array: 

  [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]



- Check whether a Numpy array contains a specified row

In [32]:
# Array
array = np.array([[1, 4, 2], [2, 3, 9]])
# Row
row = np.array([1, 2, 3])
print(f'Array: \n\n {array}\n')
print(f'Array: \n\n {row}\n')
# Check if row is in array
print(f'Is row in array ?: \n\n {row in array}')

Array: 

 [[1 4 2]
 [2 3 9]]

Array: 

 [1 2 3]

Is row in array ?: 

 True


- How to Remove rows in Numpy array that contains non-numeric values?

In [47]:
# Array with nan elements
array_nan = np.array([[1, 2, 3], [np.nan, 5, np.nan]])
print(f'Array NaN:\n\n {array_nan}\n')
# Removing rows with any nan element
array_without_nan = array_nan[~np.isnan(array_nan).any(axis=1)]
print(f'Array Without NaN:\n\n {array_without_nan}\n')

Array NaN:

 [[ 1.  2.  3.]
 [nan  5. nan]]

Array Without NaN:

 [[1. 2. 3.]]



- Remove single-dimensional entries from the shape of an array

In [55]:
# 2d array
array_2d = np.array([[1], [2], [3]])
print(f'2d Array:\n\n {array_2d}\n')
# Removing one dimension from array
array_1d = np.squeeze(array_2d)
print(f'1d Array: \n\n {array_1d}')

2d Array:

 [[1]
 [2]
 [3]]

1d Array: 

 [1 2 3]


- Find the number of occurrences of a sequence in a NumPy array

In [60]:
# Array with sequence
array_with_sequence = np.array([[1, 2, 3], [2, 3, 1], [1, 2, 3]])
print(f'Array with sequence:\n\n {array_with_sequence}\n\n')
# Defining pattern
pattern_sequence = '1, 2, 3'
print(f'Pattern: {pattern_sequence}\n\n')
# Counting sequence occurrence inside array
print(f'# of Occurrences: {repr(array_with_sequence).count(pattern_sequence)}')

Array with sequence:

 [[1 2 3]
 [2 3 1]
 [1 2 3]]


Pattern: 1, 2, 3


# of Occurrences: 2


- Find the most frequent value in a NumPy array

In [66]:
# Array
array = np.array([1,2,1,1,2,3,4])
print(f'Most Frequent Element of array: {np.bincount(array).argmax()}')

Most Frequent Element of array: 1



- Combining a one and a two-dimensional NumPy Array

In [74]:
# 1D array
array_1d = np.array([1,2,3])
# 2D array
array_2d = np.array([[4,5,6],[7, 8, 9]])
# iterating and combining 
for a1, a2 in np.nditer([array_1d, array_2d]):
    print(f'{a1} --> {a2}')

1 --> 4
2 --> 5
3 --> 6
1 --> 7
2 --> 8
3 --> 9


- How to build an array of all combinations of two NumPy arrays?

In [87]:
# Arrays
array1 = np.array([1, 2, 3])
array2 = np.array([9, 10, 11])
# New array with combination
np.array(np.meshgrid(array1, array2)).T.reshape(-1,3)

array([[ 1,  9,  1],
       [10,  1, 11],
       [ 2,  9,  2],
       [10,  2, 11],
       [ 3,  9,  3],
       [10,  3, 11]])


- How to add a border around a NumPy array?

In [95]:
# Original Array
original_array = np.array([[1,2], [3, 4]])
# Padded Array with 0
padded_array = np.pad(original_array, pad_width=1, mode='constant',
               constant_values=0)
print(f'Before Padding:\n\n {original_array}\n')
print(f'After Padding:\n\n {padded_array}')

Before Padding:

 [[1 2]
 [3 4]]

After Padding:

 [[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 0 0 0]]



- How to compare two NumPy arrays?


In [97]:
array1 = np.array([1,3,4,5])
array2 = np.array([0,3,2,5])
print(f'Testing if elements are equal: {array1 == array2}')
print(f'Testing if all elements are equal: {(array1 == array2).all()}')

Testing if elements are equal: [False  True False  True]
Testing if all elements are equal: False



- How to check whether specified values are present in NumPy array?

In [103]:
array = np.array([1,2,3,4,5])
np.isin([1,2], array)

array([ True,  True])

- How to get all 2D diagonals of a 3D NumPy array?

In [105]:
array = np.arange(120).reshape(3, 4, 10)
array_diagonal = np.diagonal(array, 
                       axis1 = 1,
                       axis2 = 2)
print(array)
array_diagonal

[[[  0   1   2   3   4   5   6   7   8   9]
  [ 10  11  12  13  14  15  16  17  18  19]
  [ 20  21  22  23  24  25  26  27  28  29]
  [ 30  31  32  33  34  35  36  37  38  39]]

 [[ 40  41  42  43  44  45  46  47  48  49]
  [ 50  51  52  53  54  55  56  57  58  59]
  [ 60  61  62  63  64  65  66  67  68  69]
  [ 70  71  72  73  74  75  76  77  78  79]]

 [[ 80  81  82  83  84  85  86  87  88  89]
  [ 90  91  92  93  94  95  96  97  98  99]
  [100 101 102 103 104 105 106 107 108 109]
  [110 111 112 113 114 115 116 117 118 119]]]


array([[  0,  11,  22,  33],
       [ 40,  51,  62,  73],
       [ 80,  91, 102, 113]])


- Flatten a Matrix in Python using NumPy

In [111]:
# Original array
array = np.ones((3,3))
flatten_array = array.flatten()
print(f'Original Array:\n\n  {array}\n')
print(f'Flatten Array: \n\n {flatten_array}\n')

Original Array:

  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Flatten Array: 

 [1. 1. 1. 1. 1. 1. 1. 1. 1.]




- Flatten a 2d numpy array into 1d array

In [112]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
flatten_array = array.flatten()
print(f'Original Array:\n\n  {array}\n')
print(f'Flatten Array: \n\n {flatten_array}\n')

Original Array:

  [[1 2 3]
 [4 5 6]
 [7 8 9]]

Flatten Array: 

 [1 2 3 4 5 6 7 8 9]



- Move axes of an array to new positions

In [126]:
array_zeros = np.zeros((2, 5))
print(f'Old Array: \n\n{array_zeros}\n')
array_zeros_moved = np.moveaxis(array_zeros, 0, -1)
print(f'New Array: \n\n{array_zeros_moved}\n')


Old Array: 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

New Array: 

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]




- Interchange two axes of an array

In [127]:
array = np.array([[1,2,3,4,5]])
array_changed = np.swapaxes(array, 0, 1)
print(f'Old Array: \n\n{array}\n')
print(f'New Array: \n\n{array_changed}\n')

Old Array: 

[[1 2 3 4 5]]

New Array: 

[[1]
 [2]
 [3]
 [4]
 [5]]



- NumPy – Fibonacci Series using Binet Formula


In [134]:
# Numbers to extract fibonnaci
array_numbers = np.arange(1, 10)
# Length of Array
len_numbers = len(array_numbers)
# Binet
aux_sqrt_five = np.sqrt(5)
alpha = (1 + aux_sqrt_five) / 2
beta = (1 - aux_sqrt_five) / 2
fibonacci_number = np.rint(((alpha ** array_numbers) - (beta ** array_numbers)) / (aux_sqrt_five))
print(f'Here are the first {len_numbers} elements of Fibonacci series: {fibonacci_number}')

Here are the first 9 elements of Fibonacci series: [ 1.  1.  2.  3.  5.  8. 13. 21. 34.]




- Counts the number of non-zero values in the array

In [117]:
array = [[1, 2, 0, 4, 5], [0, 0, 0, 9, 10], [0, 0, 0, 14, 15]]

print(f'Non-Zero Elements: {np.count_nonzero(array)}')

Non-Zero Elements: 8



- Count the number of elements along a given axis

In [116]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(f'Axis 0: {np.size(array, 0)}')
print(f'Axis 1: {np.size(array, 1)}')

Axis 0: 2
Axis 1: 4



- Trim the leading and/or trailing zeros from a 1-D array

In [115]:
# Array with 0
array_with_zeros = np.array([0,0, 1, 2, 3, 4, 0, 0 ,0])
# Trimed Array
trimmed_array = np.trim_zeros(array_with_zeros)
print(f'Original Array:\n\n  {array_with_zeros}\n')
print(f'Trimmed Array: \n\n {trimmed_array}\n')

Original Array:

  [0 0 1 2 3 4 0 0 0]

Trimmed Array: 

 [1 2 3 4]



- Change data type of given numpy array



- Reverse a numpy array

In [114]:
# Original array
array = np.array([1, 2, 3])
#Flipped array
flipped_array = np.flipud(array)
print(f'Original Array:\n\n  {array}\n')
print(f'Flipped Array: \n\n {flipped_array}\n')

Original Array:

  [1 2 3]

Flipped Array: 

 [3 2 1]



- How to make a NumPy array read-only?

In [136]:
# Array that we can change
array = np.ones(5)
array[0] = 17
print(f'Original Array:\n\n  {array}\n')
# Array that we can not change anymore, just read
array.flags.writeable = False
print(f'Trying change element:\n')

array[1] = 13

Original Array:

  [17.  1.  1.  1.  1.]

Trying change element:



ValueError: assignment destination is read-only

# Questions on NumPy Matrix


- Get the maximum value from given matrix

In [147]:
# Random Seed
np.random.seed(42)
# Array of random integers between 1 and 99
array_random_int = np.random.randint(1,100, size=(3,3))
# Max value
print(f'Max value in Array is: {np.max(array_random_int)}')

Max value in Array is: 93


- Get the minimum value from given matrix

In [148]:
# Random Seed
np.random.seed(42)
# Array of random integers between 1 and 99
array_random_int = np.random.randint(1,100, size=(3,3))
# Min value
print(f'Min value in Array is: {np.min(array_random_int)}')

Min value in Array is: 15


- Find the number of rows and columns of a given matrix using NumPy

In [150]:
print(f'Array of random integers has: {array_random_int.shape[0]} rows and {array_random_int.shape[1]} columns')

Array of random integers has: 3 rows and 3 columns


- Select the elements from a given matrix

In [153]:
#Slicing of array
print(f'Array:\n\n{array_random_int}\n')
print(f'Select all elements of first row:\n\n {array_random_int[0,:]}\n')

Array:

[[52 93 15]
 [72 61 21]
 [83 87 75]]

Select all elements of first row:

 [52 93 15]




- Find the sum of values in a matrix

In [151]:
print(f'Sum of all elements of array: {array_random_int.sum()}')

Sum of all elements of array: 559


- Calculate the sum of the diagonal elements of a NumPy array

In [155]:
print(f'Sum of Diagonal: {np.trace(array_random_int)}')

Sum of Diagonal: 188


- Adding and Subtracting Matrices in Python

In [157]:
array1 = np.array([[1,2,3], [4, 5, 6]])
array2 = np.array([[2, 2, 2], [2, 2, 2]])
print(f'Adding arrays: \n\n{np.add(array1, array2)}\n')
print(f'Subtracting arrays: \n\n{np.subtract(array1, array2)}\n')

Adding arrays: 

[[3 4 5]
 [6 7 8]]

Subtracting arrays: 

[[-1  0  1]
 [ 2  3  4]]




- Ways to add row/columns in numpy array


- Matrix Multiplication in NumPy

In [161]:
array1 = np.array([[1,2], [3, 4]])
array2 = np.array([[2, 3]])
print(f'Product of matrices: \n\n {np.dot(array2, array1)}')

Product of matrices: 

 [[11 16]]


- Get the eigen values of a matrix

In [165]:
eigenvalues, _ = np.linalg.eig(array_random_int)
print(f'Eigenvalues: \n\n{eigenvalues}')

Eigenvalues: 

[170.86533267 -24.93072359  42.06539093]


 - How to Calculate the determinant of a matrix using NumPy?

In [166]:
array = np.array([[5, 3], [3, 4]])
print(f'Det of Array: \n\n{np.linalg.det(array)}')

Det of Array: 

10.999999999999996


- How to inverse a matrix using NumPy

In [168]:
print(f'Inverse of Array: \n\n{np.linalg.inv(array)}')

Inverse of Array: 

[[ 0.36363636 -0.27272727]
 [-0.27272727  0.45454545]]


- How to count the frequency of unique values in NumPy array?

In [169]:
array = np.array([1, 2, 3, 3, 3, 2, 2, 1, 5, 6])
unique_elements, frequency = np.unique(array, return_counts = True)
print(f'Unique Elements: {unique_elements}')
print(f'Frequency Values: {frequency}')

Unique Elements: [1 2 3 5 6]
Frequency Values: [2 3 3 1 1]


- Multiply matrices of complex numbers using NumPy in Python

In [174]:
array_complex1 = np.array([1+2j, 3+4j])
array_complex2 = np.array([5+6j, 7+8j])

print(f'Product of complex arrays:  \n\n{np.vdot(array_complex1, array_complex2)}')

Product of complex arrays:  

(70-8j)


- Compute the outer product of two given vectors using NumPy in Python

In [176]:
array1 = np.array([1,2])
array2 = np.array([3,4])
print(f'Outer Product of arrays:  \n\n{np.outer(array1, array2)}')

Outer Product of arrays:  

[[3 4]
 [6 8]]


- Calculate inner, outer, and cross products of matrices and vectors using NumPy

In [177]:
array1 = np.array([[0, 3, 1], [4, 7, 12]])
array2 = np.array([[8, 3, 1], [4, 1, 3]])

print(f'Innert Product: \n\n {np.inner(array1, array2)}\n')
print(f'Outer Product: \n\n {np.outer(array1, array2)}\n')
print(f'Cross Product: \n\n {np.cross(array1, array2)}\n')


Innert Product: 

 [[10  6]
 [65 59]]

Outer Product: 

 [[ 0  0  0  0  0  0]
 [24  9  3 12  3  9]
 [ 8  3  1  4  1  3]
 [32 12  4 16  4 12]
 [56 21  7 28  7 21]
 [96 36 12 48 12 36]]

Cross Product: 

 [[  0   8 -24]
 [  9  36 -24]]




- Compute the covariance matrix of two given NumPy arrays

In [182]:
np.random.seed(42)
array1 = np.random.randint(1,200, (2,2))
np.random.seed(43)
array2 = np.random.randint(1,200, (2,2))
array_cov = np.cov(array1, array2)
print(f'Covariance Matrix of Two Arrays: \n\n{array_cov}')

Covariance Matrix of Two Arrays: 

[[ 2964.5 -3003.   -154.  -1078. ]
 [-3003.   3042.    156.   1092. ]
 [ -154.    156.      8.     56. ]
 [-1078.   1092.     56.    392. ]]



- Convert covariance matrix to correlation matrix using Python

In [183]:
v = np.sqrt(np.diag(array_cov))
array_outer = np.outer(v, v)
array_correlation = array_cov / array_outer
print(f'Correlation Matrix: \n\n{array_correlation}')

Correlation Matrix: 

[[ 1. -1. -1. -1.]
 [-1.  1.  1.  1.]
 [-1.  1.  1.  1.]
 [-1.  1.  1.  1.]]



- Compute the Kronecker product of two mulitdimension NumPy arrays

In [185]:
print(f'Array 1: \n\n{array1}')
print(f'Array 2: \n\n{array2}')
print(f'Kronecker Product: \n\n{np.kron(array1, array2)}')

Array 1: 

[[103 180]
 [ 93  15]]
Array 2: 

[[69 65]
 [50 22]]
Kronecker Product: 

[[ 7107  6695 12420 11700]
 [ 5150  2266  9000  3960]
 [ 6417  6045  1035   975]
 [ 4650  2046   750   330]]



- Convert the matrix into a list

In [192]:
print(f'Original Array: \n\n{array1}')
print(f'Array to list: {array1.tolist()}')


Original Array: 

[[103 180]
 [ 93  15]]
Array to list: [[103, 180], [93, 15]]


# Questions on NumPy Indexing


- Replace NumPy array elements that doesn’t satisfy the given condition

In [198]:
array = np.array([[1, 2, 3],
                  [2, 5, 5]])

print(f'Original Array: \n\n{array}')
# Substituting 5 with 0
array[array==5] = 0
print(f'Original Array: \n\n{array}')

Original Array: 

[[1 2 3]
 [2 5 5]]
Original Array: 

[[1 2 3]
 [2 0 0]]



- Return the indices of elements where the given condition is satisfied

In [201]:
array = np.array([[1, 2, 3],
                  [2, 5, 5]])
filter_condition = np.where(array<5)
print(f'Indicex of elements < 5: {filter_condition}')

Indicex of elements < 5: (array([0, 0, 0, 1]), array([0, 1, 2, 0]))


- Replace NaN values with average of columns


- Replace negative value with zero in numpy array


In [204]:
array = np.array([-1, -2, 3, 4, 5, -6])
array[array<0] = 0
array

array([0, 0, 3, 4, 5, 0])

- How to get values of an NumPy array at certain index positions?

In [240]:
# Putting array2 in position 0, 1 and 4 of array1
array1 = np.array([1, 8, 6, 7, 30])
array2 = np.array([13, 3, 63])
array1.put([0, 1, 4], array2)
array1

array([13,  3,  6,  7, 63])

- Find indices of elements equal to zero in a NumPy array

In [209]:
array = np.array([1, 0, 3])
filter_condition = np.where(array==0)
print(f'Indicex of elements = 0: {filter_condition[0]}')

Indicex of elements = 0: [1]


- How to Remove columns in Numpy array that contains non-numeric values?

In [215]:
array = np.array([[1,2,3], [4,np.nan,6], [71,81,19]])
array[:,~np.isnan(array).any(axis=1)]

array([[ 1.,  3.],
       [ 4.,  6.],
       [71., 19.]])

- How to access different rows of a multidimensional NumPy array?

In [216]:
array = np.array([[1, 2, 3], 
                  [13, 5, 63], 
                  [71, 12, 45],
                  [23, 100, 23]])
array[[1,3]]

array([[ 13,   5,  63],
       [ 23, 100,  23]])

1
- Get row numbers of NumPy array having element larger than X

In [227]:


np.random.seed(13)
array_random_int = np.random.randint(1,45, (4,4))
number = 35
print(f'Array: \n\n{array_random_int}\n')
print(f'Row indices: \n\n{np.where(np.any(array_random_int > number, axis = 1))}')


Array: 

[[19 11 17 39]
 [35 26 36 27]
 [ 3 38 14 11]
 [10 12  3 33]]

Row indices: 

(array([0, 1, 2]),)


- Get filled the diagonals of NumPy array

In [236]:
np.random.seed(13)
array_random_int = np.random.randint(1,30, (4,4))
print(f'Original Array:\n\n {array_random_int}')
np.fill_diagonal(array_random_int, 5)
print(f'New Diagonal Array: \n\n{array_random_int}')

Original Array:

 [[19 17 11 17]
 [ 7  3 21 26]
 [13 27  4 27]
 [21  3 15 23]]
New Diagonal Array: 

[[ 5 17 11 17]
 [ 7  5 21 26]
 [13 27  5 27]
 [21  3 15  5]]


- Check elements present in the NumPy array

In [237]:
array = np.array([12,2,3,4])
print(27 in array)
print(12 in array)

False
True


# Questions on NumPy Linear Algebra

- Find a matrix or vector norm using NumPy

In [241]:
array = np.array([[ 1, 2, 3],
               [4, 5, 6]])
np.linalg.norm(array)

9.539392014169456

- Calculate the QR decomposition of a given matrix using NumPy

In [242]:
Q, R = np.linalg.qr(array)
print('\nQ:\n', Q)
print('\nR:\n', R)


Q:
 [[-0.24253563 -0.9701425 ]
 [-0.9701425   0.24253563]]

R:
 [[-4.12310563 -5.33578375 -6.54846188]
 [ 0.         -0.72760688 -1.45521375]]


- Compute the condition number of a given matrix using NumPy

In [243]:
np.linalg.cond(array)

12.302245504069202

- Compute the eigenvalues and right eigenvectors of a given square array using NumPy?

In [244]:
array = np.array([[1, 2],
              [2, 3]])

w, v = np.linalg.eig(array)
  
print(f'Eigenvalues:\n {w}')

print(f'Right Eigenvectors:\n {v}')

Eigenvalues:
 [-0.23606798  4.23606798]
Right Eigenvectors:
 [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


- Calculate the Euclidean distance using NumPy

In [245]:
array1 = np.array([9,16])
array2 = np.array([6, 12])

np.linalg.norm(array1 - array2)

5.0

# Questions on NumPy Random

- Create a Numpy array with random values

In [247]:
np.random.seed(123)
array = np.random.rand(3,3)
array

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646],
       [0.9807642 , 0.68482974, 0.4809319 ]])

- How to choose elements from the list with different probability using NumPy?

In [254]:
np.random.seed(123)
list_ = [1,2,3,4,5]
np.random.choice(list_, 3)

array([3, 5, 3])


- How to get weighted random choice in Python?

In [259]:
np.random.seed(123)
np.random.choice(list_, 3, p=[0.5, 0.1, 0.1, 0.15, 0.15])

array([3, 1, 1])

- Generate Random Numbers From The Uniform Distribution using NumPy

In [267]:
np.random.seed(123)
np.random.uniform(low=0.0, high=1.0, size=5)

array([0.69646919, 0.28613933, 0.22685145, 0.55131477, 0.71946897])

- Get Random Elements form geometric distribution

In [268]:
np.random.seed(123)
np.random.geometric(p=0.15, size=5)

array([8, 3, 2, 5, 8])


- Get Random elements from Laplace distribution

In [271]:
np.random.seed(123)
np.random.laplace(0.1, 1, 5)

array([ 0.59912496, -0.45812922, -0.69031268,  0.2082865 ,  0.67792375])

- Return a Matrix of random values from a uniform distribution

In [273]:
np.random.seed(123)
np.random.uniform(0,1,size=(3,3))

array([[0.73799541, 0.18249173, 0.17545176],
       [0.53155137, 0.53182759, 0.63440096],
       [0.84943179, 0.72445532, 0.61102351]])

- Return a Matrix of random values from a Gaussian distribution


In [272]:
np.random.seed(123)
np.random.normal(0,3, size=(3,3))

array([[ 0.96631821, -0.15455316, -0.61260289],
       [ 5.9380453 , -4.8579002 , -3.34189325],
       [-1.34232216,  5.00520484, -0.43011742]])

# Questions on NumPy Sorting and Searching

- How to get the indices of the sorted array using NumPy in Python?

In [274]:
array = np.array([2, 1, 3, 15, 20, 5, 4])
np.argsort(array)

array([1, 0, 2, 6, 5, 3, 4])

- Finding the k smallest values of a NumPy array

In [275]:
k = 3
array_sorted = np.sort(array)
array_sorted[:k]

array([1, 2, 3])

- How to get the n-largest values of an array using NumPy?

In [276]:
k = 3
sorted_array = array[np.argsort(array)]
sorted_array[-k: ]

array([ 5, 15, 20])

- Sort the values in a matrix

In [286]:
array = np.array([[1,5], [4,2]])
array.sort(axis=1)
print('\n', array, '\n')
array.sort(axis=0)
print('\n', array, '\n')


 [[1 5]
 [2 4]] 


 [[1 4]
 [2 5]] 



- Filter out integers from float numpy array

In [289]:
array = np.array([1, 2.0, 2.5, 3.09])
array[array != array.astype(int)]

array([2.5 , 3.09])

- Find the indices into a sorted array

In [298]:
np.searchsorted(array, 3)

3

# Questions on NumPy Mathematics

- How to get element-wise true division of an array using Numpy?


In [301]:
array = [-1, 2, 3, 4]
np.true_divide(array, 2)

array([-0.5,  1. ,  1.5,  2. ])

- How to calculate the element-wise absolute value of NumPy array?

In [302]:
np.absolute(array)

array([1, 2, 3, 4])


- Compute the negative of the NumPy array

In [303]:
np.negative(array)

array([ 1, -2, -3, -4])

- Multiply 2d numpy array corresponding to 1d array

In [304]:
  
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([1, 2, 3])
array1 * array2[:, np.newaxis]


array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]])

- Computes the inner product of two arrays

In [306]:
array1 = np.array([2,3,4])
array2 = np.array([1,4,6])
np.inner(array1, array2)

38


- Compute the nth percentile of the NumPy array

In [314]:
array = np.arange(1,101)
np.percentile(array, q=25)

25.75



- Calculate the n-th order discrete difference along the given axis

In [317]:

array = np.array([1, 3, 45, 11, 92])
print("Second order difference : ", np.diff(array, n = 2))
print("Third order difference  : ", np.diff(array, n = 3))

Second order difference :  [ 40 -76 115]
Third order difference  :  [-116  191]



- Calculate the sum of all columns in a 2D NumPy array

In [320]:
print(f'Array: {array_random_int}')
print(f'Sum of columns: {array_random_int.sum(axis=0)}')

Array: [[ 5 17 11 17]
 [ 7  5 21 26]
 [13 27  5 27]
 [21  3 15  5]]
Sum of columns: [46 52 52 75]


- Calculate average values of two given NumPy arrays

In [323]:
array1 = np.array([1,2,3])
array2 = np.array([4, 5, 6])
mean_array = (array1+array2)/2
print(f'Array 1:{array1}')
print(f'Array 2:{array2}')
print(f'Mean Array:{mean_array}')

Array 1:[1 2 3]
Array 2:[4 5 6]
Mean Array:[2.5 3.5 4.5]



- How to compute numerical negative value for all elements in a given NumPy array?

In [330]:
print(f'Original Array: \n\n{array_random_int}\n')
print(f'Negative Array: \n\n {np.negative(array_random_int)}')

Original Array: 

[[ 5 17 11 17]
 [ 7  5 21 26]
 [13 27  5 27]
 [21  3 15  5]]

Negative Array: 

 [[ -5 -17 -11 -17]
 [ -7  -5 -21 -26]
 [-13 -27  -5 -27]
 [-21  -3 -15  -5]]


- How to get the floor, ceiling and truncated values of the elements of a numpy array?

In [333]:
array = np.array([-1.2, -1.4, 0.54, -0.5,
              1.62, 1.833, 3.1])
print(f'Floor: {np.floor(array)}')
print(f'Ceil: {np.ceil(array)}')
print(f'Trunc: {np.trunc(array)}')

Floor: [-2. -2.  0. -1.  1.  1.  3.]
Ceil: [-1. -1.  1. -0.  2.  2.  4.]
Trunc: [-1. -1.  0. -0.  1.  1.  3.]



- How to round elements of the NumPy array to the nearest integer?

In [334]:
np.rint(array)

array([-1., -1.,  1., -0.,  2.,  2.,  3.])



- Find the round off the values of the given matrix

In [335]:
array.round()

array([-1., -1.,  1., -0.,  2.,  2.,  3.])


- Determine the positive square-root of an array

In [336]:
array = np.array([4, 9, 16, 25])
np.sqrt(array)

array([2., 3., 4., 5.])

- Evaluate Einstein’s summation convention of two multidimensional NumPy arrays

In [342]:
array1 = np.array([[1, 2], [0, 27]])
array2 = np.array([[0, 33], [43, 4]])
np.einsum('mk,kn',array1, array2)

array([[  86,   41],
       [1161,  108]])

# Questions on NumPy Statistics

- Compute the median of the flattened NumPy array

In [343]:
array = np.array([1,2,3,4,5,6,7,8,9,10])
np.median(array.flatten())

5.5

- Find Mean of a List of Numpy Array

In [345]:
# List of arrays
list_arrays = [np.array([11, 5, 41]),
         np.array([12, 13, 26]),
         np.array([56, 20, 51])]
# Iterating in list_arrays and taking average of each element of the list 
for i in list_arrays:
    print(np.mean(i))

19.0
17.0
42.333333333333336


- Calculate the mean of array ignoring the NaN value

In [347]:
array_with_nan = np.array([1,2,3, np.nan])
np.nanmean(array_with_nan)

2.0

- Get the mean value from given matrix

In [352]:
np.random.seed(123)
array = np.random.randint(5, 20, size=(3,3))
array.mean()

12.444444444444445

- Compute the variance of the NumPy array

In [354]:
array.var()

28.913580246913575


- Compute the standard deviation of the NumPy array

In [357]:
array.std()

5.3771349478057155

- Compute pearson product-moment correlation coefficients of two given NumPy arrays

In [358]:
array1 = np.array([1,2,3,4,5,6])
array2 = np.array([2,4,0,9, 7, 11 ])
np.corrcoef(array1, array2)

array([[1.        , 0.79593942],
       [0.79593942, 1.        ]])


- Calculate the mean across dimension in a 2D NumPy array

In [359]:
array = np.array([[100, 300], [200, 600]])
print(f'Original array: \n\n{array}\n')
print(f'Mean of each column: \n\n{array.mean(axis=0)}\n')
print(f'Mean of each row:\n\n {array.mean(axis=1)}')

Original array: 

[[100 300]
 [200 600]]

Mean of each column: 

[150. 450.]

Mean of each row:

 [200. 400.]


- Calculate the average, variance and standard deviation in Python using NumPy

In [361]:
print(f'Original array: \n\n{array}\n')
print(f'Mean of array: \n\n{array.mean()}\n')
print(f'Variance of array:\n\n {array.var()}\n')
print(f'Standard Dev. of array:\n\n {array.std()}')

Original array: 

[[100 300]
 [200 600]]

Mean of array: 

300.0

Variance of array:

 35000.0

Standard Dev. of array:

 187.08286933869707


- Describe a NumPy Array in Python

In [363]:
describe(array)

NameError: name 'describe' is not defined

# Questions on Polynomial


- Define a polynomial function

In [369]:
# p = 1*X + 2
poly1d = np.poly1d([1, 2])

9

- How to add one polynomial to another using NumPy in Python?

In [371]:
# poly1d1 = 3(x**2) + (-1)x +2
poly1d1 = (3,-1,2)

 
  
# poly1d2 = 2(x**2) + (-5)x +2
poly1d2 = (2,-5,2)
  
# add the polynomials
poly1dresult = np.polynomial.polynomial.polyadd(poly1d1,poly1d2)
  
print(poly1dresult)

[ 5. -6.  4.]


- How to subtract one polynomial to another using NumPy in Python?

In [373]:
# subtract the polynomials
poly1dresult = np.polynomial.polynomial.polysub(poly1d1,poly1d2)
print(poly1dresult)

[1. 4.]



- How to multiply a polynomial to another using NumPy in Python?

In [374]:
# multiply the polynomials
poly1dresult = np.polynomial.polynomial.polymul(poly1d1,poly1d2)
print(poly1dresult)

[  6. -17.  15. -12.   4.]



- How to divide a polynomial to another using NumPy in Python?

In [375]:
# divide the polynomials
poly1dresult = np.polynomial.polynomial.polydiv(poly1d1,poly1d2)
print(poly1dresult)

(array([1.]), array([1., 4.]))


- Find the roots of the polynomials using NumPy

In [377]:
poly_coefs = [1, 2, 3]
np.roots(poly_coefs)

array([-1.+1.41421356j, -1.-1.41421356j])

- Evaluate a 2-D polynomial series on the Cartesian product

In [378]:
array = np.array([[2, 4, 6], [1, 2, 4]]) 
cartesian_product = np.polynomial.polynomial.polygrid2d([7, 9], [8, 10], array)
print(cartesian_product)

[[2329. 3589.]
 [2875. 4431.]]


- Evaluate a 3-D polynomial series on the Cartesian product

In [379]:

array = np.array([[1, 10, 51], [19, 4, 62], [1, 12, 13]]) 
cartesian_product = np.polynomial.polynomial.polygrid3d([7, 9], [8, 10], [5, 6], array)
print(cartesian_product)

[[ 650824.  765589.]
 [1001808. 1178441.]]


# Questions on NumPy Strings
- Repeat all the elements of a NumPy array of strings
- How to split the element of a given NumPy array with spaces?
- How to insert a space between characters of all the elements of a given NumPy array?
- Find the length of each string element in the Numpy array
- Swap the case of an array of string
- Change the case to uppercase of elements of an array
- Change the case to lowercase of elements of an array
- Join String by a seperator
- Check if two same shaped string arrayss one by one
- Count the number of substrings in an array
- Find the lowest index of the substring in an array
- Get the boolean array when values end with a particular character
- More Questions on NumPy
- Different ways to convert a Python dictionary to a NumPy array
- How to convert a list and tuple into NumPy arrays?
- Ways to convert array of strings to array of floats
- Convert a NumPy array into a csv file
- How to Convert an image to NumPy array and save it to CSV file using Python?
- How to save a NumPy array to a text file?
- Load data from a text file
- Plot line graph from NumPy array
- Create Histogram using NumPy

# Libs
import numpy as np

- How to create an empty and a full NumPy array?


# NumPy Array
- How to create an empty and a full NumPy array?
- Create a Numpy array filled with all zeros
- Create a Numpy array filled with all ones
- Check whether a Numpy array contains a specified row
- How to Remove rows in Numpy array that contains non-numeric values?
- Remove single-dimensional entries from the shape of an array
- Find the number of occurrences of a sequence in a NumPy array
- Find the most frequent value in a NumPy array
- Combining a one and a two-dimensional NumPy Array
- How to build an array of all combinations of two NumPy arrays?
- How to add a border around a NumPy array?
- How to compare two NumPy arrays?
- How to check whether specified values are present in NumPy array?
- How to get all 2D diagonals of a 3D NumPy array?
- Flatten a Matrix in Python using NumPy
- Flatten a 2d numpy array into 1d array
- Move axes of an array to new positions
- Interchange two axes of an array
- NumPy – Fibonacci Series using Binet Formula
- Counts the number of non-zero values in the array
- Count the number of elements along a given axis
- Trim the leading and/or trailing zeros from a 1-D array
- Change data type of given numpy array
- Reverse a numpy array
- How to make a NumPy array read-only?